# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.49.0"

default_platform(:ios)

# VARIABLES FOR CONFIGURATION

ENV['XCODE_PROJECT'] = "TheCoordinator.xcodeproj"
# Your tegerts separeted by comma. Eg: de.quandoo.ConsumerApp.Debug,de.quandoo.ConsumerApp.Debug.QuandooWidget
ENV['TARGETS'] = "br.tntstudios.com.TheCoordinator"

platform :ios do

	before_all do |lane|

		if lane != :certificates
			# ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

			# If the GIT status is not clean, abort. We won't want to include junk in the build
			ensure_git_status_clean

			# Increase the Build number, based on commmit count
			build_number = number_of_commits
	    	increment_build_number(build_number: build_number).to_s
	  		commit_version_bump(xcodeproj: ENV['XCODE_PROJECT'], force: true)

			# perform pod install
			# cocoapods
		end

  	end

  	desc "Runs all the tests"
  	# DOC: https://docs.fastlane.tools/actions/scan/#scan
  	lane :test do
    	scan
  	end

  	desc "Push a new beta build to TestFlight"
	lane :beta do
		# increment_build_number(xcodeproj: "TheCoordinator.xcodeproj")
		build_app(scheme: "TheCoordinator")
		upload_to_testflight
	end

	desc "Sync all keys, certificates and profiles for all targets"
  	# by running: `fastlane certificates` you'll get all certificates needed.
  	# DOC: https://docs.fastlane.tools/actions/match/
	lane :certificates do
		match(app_identifier: ENV['TARGETS'].split(","), readonly: true)
	end
	
end

